export const ADD_SERVICE = 'ADD_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const SELECT_EDIT_SERVICE = 'SELECT_EDIT_SERVICE';
export const EDIT_FILTER = 'EDIT_FILTER';
export const EDIT_SERVICE_FIELD = 'EDIT_SERVICE_FIELD';
export const VALIDATE_SERVICE_FIELD = 'VALIDATE_SERVICE_FIELD';
export const RELOAD_SERVICE_FORM = 'RELOAD_SERVICE_FORM';
